tst_rend: tst_rend.o render.o events.o model.o bitmap.o font.o raster.o
	cc68x -g tst_rend.o render.o events.o model.o bitmap.o raster.o font.o rast_asm.o -o tst_rend 

tst_rend.o: tst_rend.c render.h
	cc68x -g -c tst_rend.c

render.o: render.c render.h events.h model.h bitmap.h raster.h 
	cc68x -g -c render.c

events.o: events.c events.h
	cc68x -g -c events.c

model.o: model.c model.h
	cc68x -g -c model.c

raster.o: raster.c raster.h rast_asm.o
	cc68x -g -c raster.c

bitmap.o: bitmap.c bitmap.h font.h
	cc68x -g -c bitmap.c
	
font.o: font.c font.h
	cc68x -g -c font.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

clean:
	$(RM) *.o *.tos
