#ifndef TYPES_H
#define TYPES_H

#define SCREEN_HEIGHT 400
#define SCREEN_WIDTH 640

#define CHICKEN_HEIGHT 64
#define CHICKEN_WIDTH 64

#define MONSTER_HEIGHT 64
#define MONSTER_WIDTH 64

#define COIN_HEIGHT 15
#define COIN_WIDTH 15

#define GROUND_Y 320
typedef unsigned char UINT8;
typedef unsigned int  UINT16;
typedef unsigned long UINT32;

typedef unsigned char bool;
#define true 1
#define false 0

#endif
