tst_mod: tst_mod.o model.o events.o
	cc68x -g tst_mod.o model.o events.o -o tst_mod

tst_mod.o: tst_mod.c model.h events.h
	cc68x -g -c tst_mod.c

events.o: events.c events.h
	cc68x -g -c events.c

model.o: model.c model.h
	cc68x -g -c model.c

clean:
	$(RM) *.o *.tos
