tst_rend: tst_rend.o render.o model.o bitmap.o raster.o
	cc68x -g tst_rend.o render.o model.o bitmap.o raster.o -o tst_rend 

tst_rend.o: tst_rend.c render.h
	cc68x -g -c tst_rend.c

render.o: render.c render.h model.h bitmap.h raster.h
	cc68x -g -c render.c

tst_mod: tst_mod.o model.o events.o
	cc68x -g tst_mod.o model.o events.o -o tst_mod

tst_mod.o: tst_mod.c model.h events.h
	cc68x -g -c tst_mod.c

events.o: events.c events.h
	cc68x -g -c events.c

model.o: model.c model.h
	cc68x -g -c model.c

tst_rast: tst_rast.o raster.o font.o bitmap.o 
	cc68x -g tst_rast.o raster.o font.o bitmap.o -o tst_rast

tst_rast.o: tst_rast.c raster.h bitmap.h 
	cc68x -g -c tst_rast.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

bitmap.o: bitmap.c bitmap.h font.h
	cc68x -g -c bitmap.c
	
font.o: font.c font.h
	cc68x -g -c font.c

clean:
	$(RM) *.o *.tos
