main: main.o model.o events.o render.o bitmap.o raster.o font.o 
	cc68x -g main.o model.o events.o render.o bitmap.o raster.o font.o -o main

main.o: main.c model.h render.h events.h 
	cc68x -g -c main.c

render.o: render.c render.h model.h events.h bitmap.h raster.h
	cc68x -g -c render.c

model.o: model.c model.h
	cc68x -g -c model.c

events.o: events.c events.h 
	cc68x -g -c events.c

raster.o: raster.c raster.h
	cc68x -g -c raster.c

bitmap.o: bitmap.c bitmap.h font.h
	cc68x -g -c bitmap.c
	
font.o: font.c font.h
	cc68x -g -c font.c

clean:
	$(RM) *.o *.tos
