# Clean before compiling 
all: clean tst_musi tst_eff tst_psg 

# Targets and dependencies
tst_musi.o: tst_musi.c music.h 
	cc68x -g -c tst_musi.c

tst_musi: tst_musi.o psg.o music.o 
	cc68x -g tst_musi.o psg.o music.o -o tst_music

tst_eff.o: tst_eff.c effects.h
	cc68x -g -c tst_eff.c 

tst_eff: tst_eff.o psg.o effects.o
	cc68x -g tst_eff.o psg.o effects.o -o tst_eff

tst_psg.o: tst_psg.c psg.h TYPES.h
	cc68x -g -c tst_psg.c

tst_psg: tst_psg.o psg.o
	cc68x -g tst_psg.o psg.o -o tst_psg

music.o: music.c music.h
	cc68x -g -c music.c

effects.o: effects.c effects.h
	cc68x -g -c effects.c

psg.o: psg.c psg.h TYPES.h
	cc68x -g -c psg.c

events.o: events.c events.h
	cc68x -g -c events.c


# Clean target
clean:
	$(RM) *.o *.tos tst_musi tst_eff tst_psg 

