# Compiler
CC = cc68x

# Compiler Flags
CFLAGS = -g -c

# Target Executable
TARGET = main

# Object Files
OBJS = main.o model.o events.o render.o bitmap.o raster.o font.o video.o rast_asm.o

# Header Files (Optional for readability)
HEADERS = model.h render.h events.h bitmap.h raster.h font.h 

# Build all (clean first)
all: clean $(TARGET)

# Link the final executable
$(TARGET): $(OBJS)
	$(CC) -g $(OBJS) -o $(TARGET)

# Compile each source file into object files
main.o: main.c model.h render.h events.h video.h
	$(CC) $(CFLAGS) main.c

render.o: render.c render.h model.h events.h raster.h bitmap.h font.h
	$(CC) $(CFLAGS) render.c

model.o: model.c model.h
	$(CC) $(CFLAGS) model.c

events.o: events.c events.h
	$(CC) $(CFLAGS) events.c

raster.o: raster.c raster.h rast_asm.o
	$(CC) $(CFLAGS) raster.c

bitmap.o: bitmap.c bitmap.h font.h
	$(CC) $(CFLAGS) bitmap.c

video.o: video.s
	gen -D -L2 video.s

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

font.o: font.c font.h
	$(CC) $(CFLAGS) font.c

# Clean up
clean:
	$(RM) $(OBJS) $(TARGET)
